Route::post('ajax/getstates', 'AjaxController@getStates');
Route::post('ajax/getcities', 'AjaxController@getCities');
Route::post('ajax/posts', 'AjaxController@posts');
Route::post('ajax/editpost', 'AjaxController@editpost');
Route::post('ajax/editposts', 'AjaxController@editposts');
Route::post('ajax/editcomment','AjaxController@editcomment');
Route::post('ajax/editcomments','AjaxController@editcomments');
Route::post('ajax/like', 'AjaxController@like');
Route::post('ajax/comments/get', 'AjaxController@getCommentBox');
Route::post('ajax/comments/post', 'AjaxController@postcomment');
Route::post('ajax/post/get', 'AjaxController@getPostBox');
Route::post('/ajax/forumpostreply/get', 'AjaxController@getForumPostBox');
Route::post('ajax/getfriendslist', 'AjaxController@getfriendslist');
Route::get('ajax/getxmppuser', 'AjaxController@getxmppuser');
Route::post('ajax/search-friend', 'AjaxController@searchfriend');
Route::post('ajax/webgetlikes', 'AjaxController@webgetlikes');
Route::post('/web/ajax/getposts', 'AjaxController@getAjaxPost');
Route::post('ajax/accept','AjaxController@accept');
Route::post('ajax/reject','AjaxController@reject');
Route::post('ajax/resend','AjaxController@resend');
Route::post('ajax/remove','AjaxController@remove');
Route::post('ajax/cancelrequest','AjaxController@cancelRequest');
Route::post('profile/ajax/cancelrequest','AjaxController@cancelRequest');
Route::post('ajax/deletepost','AjaxController@deletepost');
Route::post('ajax/deletecomments','AjaxController@deletecomments');
Route::post('/ajax/deletebox','AjaxController@deletebox');
Route::post('/ajax/jobcategory','AjaxController@getJobcategory');
Route::post('/ajax/sendrequest','AjaxController@sendRequest');
Route::post('profile/ajax/sendrequest','AjaxController@sendRequest');
Route::post('ajax/sendimage','AjaxController@sendImage');
Route::post('ajax/searchfriend','AjaxController@searchfriendlist');
Route::post('ajax/searchtabfriend','AjaxController@searchTabFriend');
Route::post('/ajax/delbroadcast','AjaxController@delBroadcast');
Route::post('/ajax/sendbroadcast','AjaxController@sendBroadcast');
Route::post('/ajax/delprivategroup','AjaxController@delPrivateGroup');
Route::post('/ajax/deluser','AjaxController@delUser');
Route::post('/ajax/editgroupname','AjaxController@editGroupName');
Route::post('ajax/viewmorefriends','AjaxController@viewMoreFriends');
Route::post('ajax/viewMoreForAll','AjaxController@viewMoreForAll');
Route::post('ajax/viewmoreposts','AjaxController@viewMorePosts');
Route::post('ajax/remove-education','AjaxController@removeEducationDetails');
Route::post('ajax/send-hotmail-invitation','AjaxController@sendHotmailInvitation');
Route::post('/ajax/forumsubgroup','AjaxController@forumSubGroup');
Route::post('/private-group-detail/ajax/groupimage','AjaxController@groupImage');
Route::post('/ajax/login','AjaxController@login');
Route::post('/ajax/delforumpost','AjaxController@delForumPost');
Route::post('/ajax/editforumpost','AjaxController@editForumPost');
Route::post('/ajax/editnewforumpost','AjaxController@editNewForumPost');
Route::post('/ajax/addnewforumpost','AjaxController@addNewForumPost');
Route::post('/ajax/likeforumpost','AjaxController@likeForumPost');
Route::post('/ajax/addnewforumreply','AjaxController@addNewForumReply');
Route::post('/ajax/view-more-forum-post','AjaxController@viewMoreForumPost');
Route::post('/ajax/view-more-forum-reply','AjaxController@viewMoreForumReply');
Route::post('/ajax/view-more-forum-comment','AjaxController@viewMoreForumComment');
Route::post('/ajax/mob-country-code','AjaxController@mobCountryCode');
Route::post('/ajax/delforumreply','AjaxController@delForumReply');
Route::post('/ajax/editforumreply','AjaxController@editForumReply');
Route::post('/ajax/editnewforumreply','AjaxController@editNewForumReply');
Route::post('/ajax/likeforumreply','AjaxController@likeForumReply');
Route::post('/ajax/forumreplycomment','AjaxController@forumReplyComment');
Route::post('/ajax/del-forum-reply-comment','AjaxController@delForumReplyComment');
Route::post('/ajax/getsubforums','AjaxController@getSubForums');
Route::post('/ajax/getsubforums-2','AjaxController@getSubForums2');
Route::post('/ajax/view-more-search-forum','AjaxController@viewMoreSearchForum');
Route::post('/ajax/get-path','AjaxController@getCurrentPath');
Route::post('/ajax/forum-del-confirm','AjaxController@forumDelConfirm');
Route::post('/ajax/leaveprivategroup','AjaxController@leavePrivateGroup');